name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x' # Brug den ønskede version af .NET Core SDK

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
